// <auto-generated />
using System;
using ClashToday.CommonServices.PinValidator.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClashToday.CommonServices.PinValidator.Infrastructure.Migrations
{
    [DbContext(typeof(ContextDb))]
    partial class ContextDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClashToday.CommonServices.PinValidator.Business.Domain.Ciudad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreCiudad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PaisId")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("Ciudad");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 620, DateTimeKind.Utc).AddTicks(2650),
                            NombreCiudad = "Ciudad de México",
                            PaisId = 113,
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 620, DateTimeKind.Utc).AddTicks(2746),
                            NombreCiudad = "Guadalajara",
                            PaisId = 113,
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 620, DateTimeKind.Utc).AddTicks(2761),
                            NombreCiudad = "Monterrey",
                            PaisId = 113,
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 620, DateTimeKind.Utc).AddTicks(2770),
                            NombreCiudad = "Puebla",
                            PaisId = 113,
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 620, DateTimeKind.Utc).AddTicks(2779),
                            NombreCiudad = "Tijuana",
                            PaisId = 113,
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 620, DateTimeKind.Utc).AddTicks(2789),
                            NombreCiudad = "León",
                            PaisId = 113,
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 620, DateTimeKind.Utc).AddTicks(2798),
                            NombreCiudad = "Mérida",
                            PaisId = 113,
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 620, DateTimeKind.Utc).AddTicks(2807),
                            NombreCiudad = "Cancún",
                            PaisId = 113,
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 620, DateTimeKind.Utc).AddTicks(2816),
                            NombreCiudad = "San Luis Potosí",
                            PaisId = 113,
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 620, DateTimeKind.Utc).AddTicks(2826),
                            NombreCiudad = "Querétaro",
                            PaisId = 113,
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 620, DateTimeKind.Utc).AddTicks(2835),
                            NombreCiudad = "Veracruz",
                            PaisId = 113,
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 620, DateTimeKind.Utc).AddTicks(2864),
                            NombreCiudad = "Chihuahua",
                            PaisId = 113,
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 620, DateTimeKind.Utc).AddTicks(2881),
                            NombreCiudad = "Toluca",
                            PaisId = 113,
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 620, DateTimeKind.Utc).AddTicks(2896),
                            NombreCiudad = "Saltillo",
                            PaisId = 113,
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 15,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 620, DateTimeKind.Utc).AddTicks(2910),
                            NombreCiudad = "Aguascalientes",
                            PaisId = 113,
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 16,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 620, DateTimeKind.Utc).AddTicks(2924),
                            NombreCiudad = "Hermosillo",
                            PaisId = 113,
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 17,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 620, DateTimeKind.Utc).AddTicks(2936),
                            NombreCiudad = "La Paz",
                            PaisId = 113,
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 18,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 620, DateTimeKind.Utc).AddTicks(2951),
                            NombreCiudad = "Matamoros",
                            PaisId = 113,
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 19,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 620, DateTimeKind.Utc).AddTicks(2965),
                            NombreCiudad = "Culiacán",
                            PaisId = 113,
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 20,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 620, DateTimeKind.Utc).AddTicks(2979),
                            NombreCiudad = "Durango",
                            PaisId = 113,
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 21,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 620, DateTimeKind.Utc).AddTicks(2993),
                            NombreCiudad = "Torreón",
                            PaisId = 113,
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 22,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 620, DateTimeKind.Utc).AddTicks(3007),
                            NombreCiudad = "Colima",
                            PaisId = 113,
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 23,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 620, DateTimeKind.Utc).AddTicks(3020),
                            NombreCiudad = "Oaxaca",
                            PaisId = 113,
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 24,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 620, DateTimeKind.Utc).AddTicks(3034),
                            NombreCiudad = "Tuxtla Gutiérrez",
                            PaisId = 113,
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 25,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 620, DateTimeKind.Utc).AddTicks(3049),
                            NombreCiudad = "Pachuca",
                            PaisId = 113,
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 26,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 620, DateTimeKind.Utc).AddTicks(3063),
                            NombreCiudad = "Irapuato",
                            PaisId = 113,
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 27,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 620, DateTimeKind.Utc).AddTicks(3075),
                            NombreCiudad = "Cabo San Lucas",
                            PaisId = 113,
                            UsuarioCreacion = "System"
                        });
                });

            modelBuilder.Entity("ClashToday.CommonServices.PinValidator.Business.Domain.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CiudadId")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CveUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumIdentificacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TipoIdentificacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CiudadId");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("ClashToday.CommonServices.PinValidator.Business.Domain.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombrePais")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pais");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6566),
                            NombrePais = "Afganistán",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6754),
                            NombrePais = "Albania",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6764),
                            NombrePais = "Alemania",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6771),
                            NombrePais = "Andorra",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6778),
                            NombrePais = "Angola",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6787),
                            NombrePais = "Antigua y Barbuda",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6794),
                            NombrePais = "Arabia Saudita",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6801),
                            NombrePais = "Argelia",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6807),
                            NombrePais = "Argentina",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6814),
                            NombrePais = "Armenia",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6821),
                            NombrePais = "Australia",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6828),
                            NombrePais = "Austria",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6834),
                            NombrePais = "Azerbaiyán",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6841),
                            NombrePais = "Bahamas",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 15,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6847),
                            NombrePais = "Bahréin",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 16,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6855),
                            NombrePais = "Bangladés",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 17,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6862),
                            NombrePais = "Barbados",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 18,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6869),
                            NombrePais = "Bielorrusia",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 19,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6876),
                            NombrePais = "Bélgica",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 20,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6883),
                            NombrePais = "Belice",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 21,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6890),
                            NombrePais = "Benín",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 22,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6896),
                            NombrePais = "Bhután",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 23,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6903),
                            NombrePais = "Bolivia",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 24,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6910),
                            NombrePais = "Bosnia y Herzegovina",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 25,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6916),
                            NombrePais = "Botsuana",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 26,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6923),
                            NombrePais = "Brasil",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 27,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6929),
                            NombrePais = "Brunéi",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 28,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6935),
                            NombrePais = "Bulgaria",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 29,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6941),
                            NombrePais = "Burkina Faso",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 30,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6948),
                            NombrePais = "Burundi",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 31,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6954),
                            NombrePais = "Cabo Verde",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 32,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6960),
                            NombrePais = "Camboya",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 33,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6967),
                            NombrePais = "Camerún",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 34,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6975),
                            NombrePais = "Canadá",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 35,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6982),
                            NombrePais = "República Centroafricana",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 36,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6990),
                            NombrePais = "Chad",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 37,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(6996),
                            NombrePais = "Chile",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 38,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7003),
                            NombrePais = "China",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 39,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7009),
                            NombrePais = "Colombia",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 40,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7015),
                            NombrePais = "Comoras",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 41,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7021),
                            NombrePais = "Congo, República del",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 42,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7028),
                            NombrePais = "Congo, República Democrática del",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 43,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7036),
                            NombrePais = "Costa Rica",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 44,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7043),
                            NombrePais = "Croacia",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 45,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7050),
                            NombrePais = "Cuba",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 46,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7056),
                            NombrePais = "Chipre",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 47,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7062),
                            NombrePais = "República Checa",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 48,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7069),
                            NombrePais = "Dinamarca",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 49,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7076),
                            NombrePais = "Dominica",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 50,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7082),
                            NombrePais = "República Dominicana",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 51,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7116),
                            NombrePais = "Ecuador",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 52,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7122),
                            NombrePais = "Egipto",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 53,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7130),
                            NombrePais = "El Salvador",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 54,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7136),
                            NombrePais = "Emiratos Árabes Unidos",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 55,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7143),
                            NombrePais = "Equatorial Guinea",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 56,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7149),
                            NombrePais = "Eritrea",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 57,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7155),
                            NombrePais = "Eslovenia",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 58,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7162),
                            NombrePais = "España",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 59,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7168),
                            NombrePais = "Estados Unidos",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 60,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7175),
                            NombrePais = "Estonia",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 61,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7181),
                            NombrePais = "Eswatini",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 62,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7187),
                            NombrePais = "Etiopía",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 63,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7193),
                            NombrePais = "Filipinas",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 64,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7199),
                            NombrePais = "Finlandia",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 65,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7205),
                            NombrePais = "Francia",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 66,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7212),
                            NombrePais = "Gambia",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 67,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7219),
                            NombrePais = "Georgia",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 68,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7225),
                            NombrePais = "Ghana",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 69,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7231),
                            NombrePais = "Grecia",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 70,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7237),
                            NombrePais = "Granada",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 71,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7243),
                            NombrePais = "Guatemala",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 72,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7249),
                            NombrePais = "Guyana",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 73,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7255),
                            NombrePais = "Guinea",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 74,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7261),
                            NombrePais = "Guinea-Bisáu",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 75,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7269),
                            NombrePais = "Guinea Ecuatorial",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 76,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7275),
                            NombrePais = "Haití",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 77,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7282),
                            NombrePais = "Honduras",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 78,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7288),
                            NombrePais = "Hungría",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 79,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7294),
                            NombrePais = "India",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 80,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7300),
                            NombrePais = "Indonesia",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 81,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7306),
                            NombrePais = "Irak",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 82,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7312),
                            NombrePais = "Irán",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 83,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7319),
                            NombrePais = "Irlanda",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 84,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7325),
                            NombrePais = "Islacia",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 85,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7331),
                            NombrePais = "Islas Marshall",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 86,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7337),
                            NombrePais = "Islas Salomón",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 87,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7343),
                            NombrePais = "Islas Seychelles",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 88,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7350),
                            NombrePais = "Italia",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 89,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7356),
                            NombrePais = "Jamaica",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 90,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7362),
                            NombrePais = "Japón",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 91,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7374),
                            NombrePais = "Jordania",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 92,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7385),
                            NombrePais = "Kazajistán",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 93,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7396),
                            NombrePais = "Kenia",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 94,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7407),
                            NombrePais = "Kirguistán",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 95,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7416),
                            NombrePais = "Kiribati",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 96,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7425),
                            NombrePais = "Kuwait",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 97,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7436),
                            NombrePais = "Laos",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 98,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7446),
                            NombrePais = "Latvia",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 99,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7456),
                            NombrePais = "Líbano",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 100,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7467),
                            NombrePais = "Liberia",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 101,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7481),
                            NombrePais = "Libia",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 102,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7492),
                            NombrePais = "Liechtenstein",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 103,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7503),
                            NombrePais = "Lituania",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 104,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7514),
                            NombrePais = "Luxemburgo",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 105,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7525),
                            NombrePais = "Madagascar",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 106,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7565),
                            NombrePais = "Malasia",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 107,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7572),
                            NombrePais = "Malaui",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 108,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7578),
                            NombrePais = "Maldivas",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 109,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7584),
                            NombrePais = "Malta",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 110,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7590),
                            NombrePais = "Marruecos",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 111,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7596),
                            NombrePais = "Mauricio",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 112,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7602),
                            NombrePais = "Mauritania",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 113,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7608),
                            NombrePais = "México",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 114,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7615),
                            NombrePais = "Micronesia",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 115,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7621),
                            NombrePais = "Mónaco",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 116,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7627),
                            NombrePais = "Mongolia",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 117,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7633),
                            NombrePais = "Mozambique",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 118,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7639),
                            NombrePais = "Namibia",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 119,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7645),
                            NombrePais = "Nauru",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 120,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7651),
                            NombrePais = "Nepal",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 121,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7657),
                            NombrePais = "Nicaragua",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 122,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7663),
                            NombrePais = "Nigeria",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 123,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7668),
                            NombrePais = "Noruega",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 124,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7674),
                            NombrePais = "Nueva Zelanda",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 125,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7680),
                            NombrePais = "Omán",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 126,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7686),
                            NombrePais = "Países Bajos",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 127,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7693),
                            NombrePais = "Pakistán",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 128,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7699),
                            NombrePais = "Panamá",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 129,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7706),
                            NombrePais = "Paraguay",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 130,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7713),
                            NombrePais = "Perú",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 131,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7719),
                            NombrePais = "Polonia",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 132,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7725),
                            NombrePais = "Portugal",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 133,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7731),
                            NombrePais = "Reino Unido",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 134,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7737),
                            NombrePais = "República del Congo",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 135,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7744),
                            NombrePais = "República Dominicana",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 136,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7750),
                            NombrePais = "Rumanía",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 137,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7756),
                            NombrePais = "Rusia",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 138,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7762),
                            NombrePais = "Rwanda",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 139,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7768),
                            NombrePais = "San Cristóbal y Nieves",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 140,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7774),
                            NombrePais = "San Marino",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 141,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7780),
                            NombrePais = "San Vicente y las Granadinas",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 142,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7787),
                            NombrePais = "Santo Tomé y Príncipe",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 143,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7793),
                            NombrePais = "Senegal",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 144,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7799),
                            NombrePais = "Serbia",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 145,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7805),
                            NombrePais = "Seychelles",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 146,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7811),
                            NombrePais = "Singapur",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 147,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7817),
                            NombrePais = "Eslovaquia",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 148,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7823),
                            NombrePais = "Eslovenia",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 149,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7829),
                            NombrePais = "Somalia",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 150,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7835),
                            NombrePais = "Sudáfrica",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 151,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7841),
                            NombrePais = "Sudán",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 152,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7870),
                            NombrePais = "Sudán del Sur",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 153,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7878),
                            NombrePais = "Suecia",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 154,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7884),
                            NombrePais = "Suiza",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 155,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7890),
                            NombrePais = "Siria",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 156,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7896),
                            NombrePais = "Tailandia",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 157,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7902),
                            NombrePais = "Tanzania",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 158,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7908),
                            NombrePais = "Timor Oriental",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 159,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7914),
                            NombrePais = "Togo",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 160,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7920),
                            NombrePais = "Tonga",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 161,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7926),
                            NombrePais = "Trinidad y Tobago",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 162,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7932),
                            NombrePais = "Túnez",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 163,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7938),
                            NombrePais = "Turkmenistán",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 164,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7945),
                            NombrePais = "Turquía",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 165,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7951),
                            NombrePais = "Tuvalu",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 166,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7957),
                            NombrePais = "Ucrania",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 167,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7963),
                            NombrePais = "Uganda",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 168,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7969),
                            NombrePais = "Uruguay",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 169,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7975),
                            NombrePais = "Uzbekistán",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 170,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7981),
                            NombrePais = "Vanuatu",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 171,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7987),
                            NombrePais = "Vaticano",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 172,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7993),
                            NombrePais = "Venezuela",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 173,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(7999),
                            NombrePais = "Vietnam",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 174,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(8005),
                            NombrePais = "Yemen",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 175,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(8012),
                            NombrePais = "Zambia",
                            UsuarioCreacion = "System"
                        },
                        new
                        {
                            Id = 176,
                            Activo = true,
                            FechaCreacion = new DateTime(2024, 10, 9, 8, 22, 45, 618, DateTimeKind.Utc).AddTicks(8017),
                            NombrePais = "Zimbabue",
                            UsuarioCreacion = "System"
                        });
                });

            modelBuilder.Entity("ClashToday.CommonServices.PinValidator.Business.Domain.Ciudad", b =>
                {
                    b.HasOne("ClashToday.CommonServices.PinValidator.Business.Domain.Pais", "Pais")
                        .WithMany("Sucursales")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("ClashToday.CommonServices.PinValidator.Business.Domain.Cliente", b =>
                {
                    b.HasOne("ClashToday.CommonServices.PinValidator.Business.Domain.Ciudad", "Ciudad")
                        .WithMany("Cliente")
                        .HasForeignKey("CiudadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ciudad");
                });

            modelBuilder.Entity("ClashToday.CommonServices.PinValidator.Business.Domain.Ciudad", b =>
                {
                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ClashToday.CommonServices.PinValidator.Business.Domain.Pais", b =>
                {
                    b.Navigation("Sucursales");
                });
#pragma warning restore 612, 618
        }
    }
}
